import type { CSSProperties } from "react";

export const s = {
  card: (accepted: boolean): CSSProperties => ({
    display: "flex",
    gap: 16,
    padding: "16px 16px 14px 18px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
    marginBottom: 12,
  }),
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  rule: { fontSize: 14.5, fontWeight: 600, fontStyle: "italic", lineHeight: 1.4 } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 7,
    background: "var(--code-bg)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  evidenceLink: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    textDecoration: "none",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  iconButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    padding: 2,
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.6,
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  confidenceBar: { width: 90 } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 8, width: 150, flexShrink: 0 } satisfies CSSProperties,
  editGrid: { display: "grid", gridTemplateColumns: "1fr 180px", gap: 10, alignItems: "start" } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies CSSProperties,
  error: { fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
};
