import type { CSSProperties } from "react";

export const s = {
  page: { maxWidth: 860, margin: "0 auto", padding: "24px 0 48px" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 6 } satisfies CSSProperties,
  titleBlock: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  title: { fontSize: 22, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  repo: { color: "var(--accent-text)" } satisfies CSSProperties,
  subtitle: { fontSize: 13.5, color: "var(--text-secondary)", margin: "6px 0 0" } satisfies CSSProperties,
  stats: { fontSize: 12, color: "var(--text-muted)", margin: "4px 0 0" } satisfies CSSProperties,
  toolbar: { display: "flex", alignItems: "center", gap: 12, margin: "18px 0 14px" } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-muted)", flex: 1 } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)", padding: "12px 2px" } satisfies CSSProperties,
  linkButton: {
    background: "none",
    border: "none",
    padding: "8px 0",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--text-secondary)",
    textDecoration: "underline",
  } satisfies CSSProperties,
  rejectedList: { marginTop: 8 } satisfies CSSProperties,
  stack: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  scanning: { fontSize: 13, color: "var(--text-muted)", marginTop: 10 } satisfies CSSProperties,
  created: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    margin: "16px 0 0",
    padding: "10px 14px",
    borderRadius: 7,
    border: "1px solid var(--ok)",
    background: "var(--ok-bg)",
    fontSize: 13,
  } satisfies CSSProperties,
  createdText: { flex: 1 } satisfies CSSProperties,
  createdLink: { color: "var(--accent-text)", fontWeight: 500 } satisfies CSSProperties,
  dismiss: { background: "none", border: "none", cursor: "pointer", color: "var(--text-muted)", fontSize: 16 } satisfies CSSProperties,
};
