import type { CSSProperties } from "react";

const LINE = 20;

export const s = {
  frame: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-primary)",
    overflow: "hidden",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "7px 10px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
  } satisfies CSSProperties,
  file: { color: "var(--text-secondary)" } satisfies CSSProperties,
  unsaved: { color: "var(--warn)" } satisfies CSSProperties,
  tokens: { color: "var(--text-muted)", marginLeft: "auto" } satisfies CSSProperties,
  modes: { display: "flex", gap: 2 } satisfies CSSProperties,
  mode: (active: boolean): CSSProperties => ({
    padding: "2px 8px",
    borderRadius: 4,
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    background: active ? "var(--bg-hover)" : "none",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
  }),
  body: { display: "flex" } satisfies CSSProperties,
  gutter: (rows: number): CSSProperties => ({
    margin: 0,
    padding: "10px 8px",
    minWidth: 38,
    textAlign: "right",
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    lineHeight: `${LINE}px`,
    height: rows * LINE + 20,
    overflow: "hidden",
    borderRight: "1px solid var(--border)",
    userSelect: "none",
  }),
  textarea: {
    flex: 1,
    margin: 0,
    padding: 10,
    border: "none",
    outline: "none",
    resize: "vertical",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: `${LINE}px`,
    whiteSpace: "pre",
    overflowWrap: "normal",
  } satisfies CSSProperties,
  preview: (rows: number): CSSProperties => ({
    padding: "12px 16px",
    minHeight: rows * LINE + 20,
    maxHeight: rows * LINE * 2,
    overflow: "auto",
  }),
  hint: {
    padding: "6px 10px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
};
