import type { CSSProperties } from "react";

/** Co-located styles for IntentCard. CSS variables only. */
export const s = {
  stack: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  headerRight: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  quote: {
    fontSize: 14,
    fontStyle: "italic",
    lineHeight: 1.55,
    color: "var(--text-primary)",
    margin: 0,
  } satisfies CSSProperties,
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 20,
  } satisfies CSSProperties,
  columnTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  item: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  itemIcon: (color: string): CSSProperties => ({ color, flexShrink: 0, marginTop: 3 }),
  none: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  divider: {
    borderTop: "1px solid var(--border)",
    paddingTop: 14,
  } satisfies CSSProperties,
  badgeRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  rowLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  sourcesRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    borderTop: "1px solid var(--border)",
    paddingTop: 14,
  } satisfies CSSProperties,
  sourceMuted: { opacity: 0.7 } satisfies CSSProperties,
  meta: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--warn)",
    margin: 0,
  } satisfies CSSProperties,
  warningIcon: { flexShrink: 0, marginTop: 3 } satisfies CSSProperties,
  muted: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 6,
  } satisfies CSSProperties,
  emptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    margin: 0,
  } satisfies CSSProperties,
  emptyAction: { marginTop: 6 } satisfies CSSProperties,
} as const;
