import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 900 } satisfies CSSProperties,
  headRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 } satisfies CSSProperties,
  heading: { fontSize: 15, fontWeight: 600 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    width: 260,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    background: "none",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", margin: "0 0 12px" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (linked: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid " + (dragging ? "var(--accent)" : "var(--border)"),
    background: linked ? "var(--bg-elevated)" : "var(--bg-surface)",
    position: "relative",
    zIndex: dragging ? 2 : undefined,
  }),
  handle: {
    display: "inline-flex",
    padding: 2,
    border: "none",
    background: "none",
    color: "var(--text-muted)",
    cursor: "grab",
    touchAction: "none",
  } satisfies CSSProperties,
  handleSpace: { width: 18, flexShrink: 0 } satisfies CSSProperties,
  name: { fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  disabled: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  type: { marginLeft: "auto" } satisfies CSSProperties,
  divider: { height: 1, background: "var(--border)", margin: "8px 0" } satisfies CSSProperties,
};
