import type { CSSProperties } from "react";

export const s = {
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  body: { padding: 24 } satisfies CSSProperties,
  /** Visually hidden but still reachable by assistive tech and automation. */
  fileInput: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  source: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  drop: (over: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "28px 16px",
    borderRadius: 8,
    border: `1px dashed ${over ? "var(--accent)" : "var(--border-strong)"}`,
    background: over ? "var(--accent-bg)" : "var(--bg-primary)",
    color: "var(--text-secondary)",
    fontSize: 13,
  }),
  link: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--accent)",
    cursor: "pointer",
    fontSize: 13,
  } satisfies CSSProperties,
  or: { textAlign: "center", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  urlRow: { display: "flex", gap: 8, alignItems: "center" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  preview: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  trust: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  grid: { display: "grid", gridTemplateColumns: "2fr 1fr", gap: 14 } satisfies CSSProperties,
  box: {
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  boxTitle: { fontSize: 12, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 4 } satisfies CSSProperties,
  ul: { margin: "6px 0 0", paddingLeft: 18, fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  rendered: {
    maxHeight: 320,
    overflow: "auto",
    padding: "12px 16px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
};
